### ISSUE TITLE
I am sorry

### ISSUE THREAD

**Issue by STOKYS** [SeezoCode/MultiplayerSnakeGame#2]
*I've made a severe and continuous lapse in my judgement and I don't expect to be forgiven. I'm simply here to apologize. So what we came across that day on github.com was obviously unplanned and the reactions you saw on the Issues tab were raw, they were unfiltered. None of us knew how to react or how to feel. I should have never posted the comment. I should have pushed the keyboard away, and stopped typing what we were going through. There's a lot of things I should have done differently, but I didn't, and for that from the bottom of my heart, I am sorry. I want to apologize to the internet, I want to apologize to anyone who's seen the comment, I want to apologize to anyone who has been affected or touched by mental illness, or depression, or suicide. But, most importantly, I want to apologize to the victim and his family. For, my fans, who are defending my actions, please don't, they do not deserve to be defended. The goal of my content is always to entertain, to push the boundaries, to be all inclusive and in the world I live in I share almost everything I do. The intent is never to be heartless, cruel, or malicious. Like I said, I made a huge mistake, I don't expect to be forgiven, I'm just here to apologize. I'm ashamed of myself. I'm disappointed in myself, and I promise to be better. I will be better, thank you.*

**Can I be your stylist?**

**Comment by SeezoCode** [comment]
Dear {Recipient}

I accept your deepest apologies for { who's} mistake in regard to {state mistake}.

I believe it was not { insert guilty person } intention to create such an awkward and embarrassing situation for {me, institution, the team, company, etc…}.

If there was any good that came out of this unfortunate experience, it is that I have grown and learned alternative approaches to these situations.

Please feel free to let me know of your thoughts and concerns over this matter. You can reach me at { github or reddit }. 

Sincerely,
SeezoCode
